/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    war
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation("org.acegisecurity:acegi-security:1.0.2")
    implementation("jfree:jfreechart:1.0.0")
    implementation("org.hibernate:hibernate:3.2.5.ga") {
        exclude(group = "javax.transaction", module = "jta")
    }
    implementation("javax.mail:mail:1.4")
    implementation("org.springframework:spring:2.5.1")
    implementation("org.springframework:spring-webmvc:2.5.1")
    implementation("org.springmodules:spring-modules-lucene:0.8") {
        exclude(group = "org.apache", module = "poi")
        exclude(group = "org.apache", module = "poi-scratchpad")
        exclude(group = "jexcelapi", module = "jxl")
    }
    implementation("org.apache.wicket:wicket:1.3.7")
    implementation("org.apache.wicket:wicket-extensions:1.3.7")
    implementation("poi:poi:2.5.1-final-20040804")
    implementation("org.tmate:javasvn:1.0.3")
    implementation("commons-dbcp:commons-dbcp:1.2.2")
    runtimeOnly("jaxen:jaxen:1.1-beta-9") {
        exclude(group = "xom", module = "xom")
    }
    runtimeOnly("geronimo-spec:geronimo-spec-jta:1.0.1B-rc4")
    runtimeOnly("org.slf4j:slf4j-log4j12:1.4.2")
    runtimeOnly("org.slf4j:jcl104-over-slf4j:1.4.2")
    runtimeOnly("org.beanshell:bsh:2.0b4")
    runtimeOnly("hsqldb:hsqldb:1.8.0.1")
    runtimeOnly("cas:casclient:2.1.1")
    runtimeOnly("net.sf.ehcache:ehcache:1.2.4")
    testImplementation("junit:junit:3.8.1")
    testImplementation("org.springframework:spring-test:2.5.1")
    providedCompile("javax.servlet:servlet-api:2.4")
}

group = "info.jtrac"
version = "2.2.0"
description = "JTrac"
java.sourceCompatibility = JavaVersion.VERSION_1_8

sourceSets {
    main {
        resources {
            srcDir("src/main/java")
            includes.add("**/*.html")
            includes.add("**/*.properties")
        }
    }
}

tasks.withType<Test> {
    enabled = false
}

tasks.named("compileTestJava") {
    enabled = false
}

tasks.named<War>("war") {
    archiveFileName.set("jtrac.war")
}
